### ISSUE TITLE
pip requirements.txt

### ISSUE THREAD

**Issue by gregoryng** [cgrima/subradar#4]
Would you mind implementing a requirements.txt file for subradar, which lists all of the external pip libraries required?  You can mention how to use it in your README.md.  It looks like this is mainly mpmath and scipy.  numpy follows automatically from scipy.

This would help systematically track what version of scipy and mpmath you need, and also we will use it as part of the installation procedure for the svv code (by telling people to install the requirements for subradar) AND svv, since subradar is a submodule.  Then if you need to update the requirements for subradar, this can happen systematically.

https://pip.pypa.io/en/stable/user_guide/#requirements-files

You probably want to change the output of pip freeze to be >= rather than ==

**Comment by cgrima** [comment]
I can work on that, yes. Another option would be to make a distribution package that can be installed through pip (https://packaging.python.org/tutorials/packaging-projects/). It might take a bit more time to implement, but the installation for other projects would be seamless.

**Comment by gregoryng** [comment]
Yes, that would be a good option, too.  Actually formalizing a release process would be very nice for our development process, if you did it for this and for rsr. 

I can leave that to you, I don't know how long it takes, but it would be nice.  If you think you'll do that on some fixed timeline (doesn't have to be too soon), then no need to do the requirements.txt as an intermediate.

**Comment by gregoryng** [comment]
You might need to think about package naming for rsr: https://pypi.org/project/pyrsr/

**Comment by cgrima** [comment]
Hi Greg,

You can now install subradar and rsr through pip

`pip install rsr subradar`

I let you make the necessary modifications in the sds hierarchy to handle these packages through pip. Let me know when this is done so that I could test.

From now on, the pip versions will mirror the git tags (all the git tags might not be pushed to pip, though)

**Comment by gregoryng** [comment]
Hi Cyril, I was able to install the packages on sds so I think this is closed.

I guess since the setup.py has an installation requirements, that is probably good enough.  I haven't read the guide on how to make packages, but you may want to make your setup.py specify minimum versions for each of  the dependencies.

But what you've done is probably good enough to close this issue.
